### ISSUE TITLE
Limiting concurrency of tests

### ISSUE THREAD

**Issue by yomed** [avajs/ava#1095]
## Description

I have about 15,000 tests that I run in a single file, each of which tests a url variant through `supertest`. If I run the tests with `--serial`, they pass. However, I can only run about a few hundred tests otherwise. After that, I guess that my server chokes and can't handle that many requests at the same time, so the tests start failing with assorted supertest errors. The tests here naturally fit in a single file due to the setup:

``` js
pages.forEach(function (page) {
    variants.forEach(function (variant) {
        langs.forEach(function (lang) {
            test.cb(...supertest(page + variant + lang)...);
        });
    });
});
```

In this scenario I would like to limit the test concurrency rather than the currently supported file concurrency. I'm coming from `mocha`, so should I be handling these differently?
## Environment

```
node 4.4.5
ava 0.16.0
npm 2.14.9
```

**Comment by capaj** [comment]
funny, I just came here to start the same issue. I am also experiencing performance problems when I have too many test files.
@yomed you can fix your problem with `-c 4`

BTW I think ava should by default limit the number of concurrent tests to the number of available procesor cores on the current machine. That way optimal performance is achieved on my experience.

**Comment by sindresorhus** [comment]
@capaj This is about tests, not test files.

> BTW I think ava should by default limit the number of concurrent tests to the number of available procesor cores on the current machine. That way optimal performance is achieved on my experience.

We might do that for test files (see open issue about it somewhere), but it does not make sense for tests.

**Comment by novemberborn** [comment]
@yomed if possible I'd recommend breaking up your tests into several files. Perhaps you could use a helper to generate them, and then create a test file for each language or variant?

Alternatively you could build your own concurrency limiter. If you can get a promise for your test result then [`throat`](https://www.npmjs.com/package/throat) may be useful.

**Comment by yomed** [comment]
@novemberborn Thanks for the suggestions. Splitting the tests up into multiple files seem a bit too hacky/overkill for this, but I can see that manually throttling promises has some... promise. Although even with that, I think I'd have to weigh the extra cost in complexity, and perhaps ava isn't currently well-suited to this type of scenario.

**Comment by tjbenton** [comment]
This would be a an awesome feature 👍. I have broken my tests out into 13 different files and between those files I have over 1000 tests. If the file has async tests and it has 200+ tests and 150 of those are very cpu intensive. I could run them serially, but that would add several minutes onto the test time but If I could limit the tests that are running to 10 or 20 then it wouldn't bring my computer to a crawl and speed up the more intensive tests.

**Comment by novemberborn** [comment]
@tjbenton does limiting the concurrency of test *file* execution help (the  experimental `concurrency` option)? Due to the event loop CPU intensive tests will be blocking within a test file anyway, so I'm not sure how running them serially would make a difference really. I wonder if you're inadvertently executing too many intensive tests in concurrent processes.

I think limiting the concurrency of tests can be helpful when the test run consumes too many resources, e.g. server capacity or memory.

**Comment by tjbenton** [comment]
Limiting the number of files running doesn't help much Because some of the test files have 15-50 tests and 3 of the files have 300+ tests. For the most part the majority of the functions that are being tested are async functions so they're none blocking, so running them serially does help the performance of each test but it takes twice as long. If I run the tests with `--concurrency 1` it does help slightly but not by too much since there're multiple files with 300+ tests that are cpu intensive. 

I ran the different tests using the `time` command and this is what they returned.

```
ava --verbose    294.41s user 8.35s system 237% cpu 2:07.75 total

ava --concurrency 1 --verbose    280.67s user 6.85s system 105% cpu 4:31.70 total
```

This is what happens If I change the tests in the 3 files with the most tests to be run serial

```
ava --verbose --concurrency 2    252.14s user 5.67s system 105% cpu 4:21.81 total
```

I think that if I could specify that only a certain amount of tests can run at the same time then it would speed it up a lot. In this app I have already added support for es6 pool and adding that it decreased the time it took to generate files by 20+ seconds so I think doing the same for ava would have a similar result.

**Comment by novemberborn** [comment]
> This is what happens If I change the tests in the 3 files with the most tests to be run serial
> 
> ava --verbose --concurrency 2    252.14s user 5.67s system 105% cpu 4:21.81 total

What happens if you use `--concurrency 2` without modifying the test files?

You're saying the tests are CPU intensive, but since Node.js uses an event loop that means the test that is currently executing blocks execution of the other tests, even if there is some initial asynchronicity that allows all tests to start at the same time. I don't see how making those tests execute serially would have a big impact, unless the problem isn't so much the CPU as it is disk I/O,  memory pressure or context switching between the worker processes.

For certain workloads where the CPU isn't the problem I can see how it could help to reduce how many tests execute concurrently within a single worker process.

**Comment by tjbenton** [comment]
I'm guessing that you're right, that when the test's are running it's running out of memory.

> What happens if you use --concurrency 2 without modifying the test files?

```
ava --verbose --concurrency 2  261.80s user 8.36s system 193% cpu 2:19.77 total
```

**Comment by novemberborn** [comment]
Thanks. So for certain tests, reducing concurrency within the test file can help performance, besides reducing how many test files are executed concurrently. That's good to know.

Question is, should AVA manage this or is this exceptional enough that it can be solved through a third-party module.

I'm leaning towards this being picked up by a third-party module to start with. Down the line we could consider including it in AVA itself.

**Comment by Kikobeats** [comment]
@novemberborn can you do an example using `throat` for that?

**Comment by novemberborn** [comment]
@Kikobeats something like this I think:

```js
const limited = require('throat')(2)

test('foo', limited(t => t.pass())
test('bar', limited(t => t.pass())
test('baz', limited(t => t.pass())
```

**Comment by novemberborn** [comment]
Your code does the same as my example, it just wraps the call to the limiter but with `throat` that's not necessary. It forwards the arguments.

The tests are invoked, yes, but the `limit` function means they don't do anything yet.

**Comment by Kikobeats** [comment]
ops it's true 🙂

**Comment by Bareus** [comment]
@novemberborn I tried out your code in my tests and noticed some problems:

1. Using throat with macro's doesn't seems to work when title is programmatically created.
```
async function macro = (t, input, expected) => {/*do async test*/}
macro.title = (providedTitle, input, expected) = { /*make test title*/ };

// this throws TypeError: Tests must have a title
test(limited(async (t, input, expected) => { await macro(t, input, expected)}), input, expected);
```

I can re-write above code to make it work like this:
```
async function macro = (t, input, expected) => {
 await limited( async() => { /*do async test*/ };
}
macro.title = (providedTitle, input, expected) = { /*make test title*/ };

// this does not throw TypeError
test(macro, input, expected);
```
This code has the problem that I could potentially run into the global timeout even though the actual test didn't start yet. The other problem, which is more of a preference from me, is that I have non-related code in my test cases which I don't really like. 

2. Using throat limits only the number of concurrent tests itself, but not their related beforeEach/afterEach hooks. As a workaround you could add throat to those hooks too, but IMO this is error prone since you could forget to add throat to a hook. Also I'm not sure how throat and ava handles concurrency internally so maybe a case could happen where all beforeEach hooks are processed first and then the tests. This could lead to a timeout since tests are inactive during the time all those beforeEach hooks are processed. 

Do you have any ideas how I can solve this problem? (Btw. I'm using ava 1.0.0-beta3 and node v8.10.0)

**Comment by novemberborn** [comment]
@Bareus have a look at https://github.com/avajs/ava/blob/master/docs/recipes/test-setup.md — you may want to avoid explicit hooks.

> I'm not sure how throat and ava handles concurrency internally so maybe a case could happen where all beforeEach hooks are processed first and then the tests.

AVA will try and run hooks for all concurrent tests. If they return promises then AVA will pause the execution of that particular test until the promise fulfills.

The timeout resets every time a test result is received. I imagine you want to limit test concurrency because it's slowing down test execution. This shouldn't then impact the timeout, because presumably you'll have some tests complete faster.

**Comment by jeremyroberts0** [comment]
For anyone else that finds this issue, the `throat` solution here no longer works, tried a couple ways

As per recommendation above:
```
function test (name, cb) {
  ava(name, throat(cb));
}
```
Seems throat does not pass through args anymore because I get `TypeError: Cannot read property 'notThrowsAsync' of undefined`.

Wrapping ava with custom async function:
```
function test (name, cb) {
  throat(() => {
    return new Promise((resolve, reject) => {
      ava(name, t => {
        const result = cb(t);
        if (result instanceof Promise) {
          result.then(resolve).catch(reject);
        } else {
          resolve();
        }
        return result;
      });
    });
  });
}
```
yields `Error: All tests and hooks must be declared synchronously in your test file, and cannot be nested within other tests or hooks.`

**Comment by novemberborn** [comment]
@jeremyroberts0 looking at the code I think it'll still work, but you can't use it directly. You need to create a limiter, as per https://github.com/avajs/ava/issues/1095#issuecomment-364657306.

I wouldn't wrap it in a function named `test`, that'll just get confusing.

Your attempt doesn't work because the second call to `ava()` is only made asynchronously when the first test completes, but subsequent `ava()` calls must be performed synchronously.

**Comment by fatihaziz** [comment]
Any update for limiting the concurrency? I hope there is configuration for it...
