### ISSUE TITLE
is and deepEqual behaviour with NaN

### ISSUE THREAD

**Issue by aureooms** [avajs/ava#1103]
```sh
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v7.0.0
linux 4.8.4-1-ARCH
$ ava --version
0.16.0
$ npm --version
3.10.9
```
Is this wanted behaviour?
```js
// test.js
import test from 'ava' ;

test( 'is' , t => {
	t.is( NaN , NaN , '?' ) ;
});

test( 'deepEqual' , t => {
	t.deepEqual( NaN , NaN , '?' ) ;
});
```

```
$ ava test.js                                                                                                                         43 ms   0

   2 failed


   1. is
   ?   
  t.is(NaN, NaN, '?')
       |    |        
       NaN  NaN      
  
      Test.fn (test.js:4:4)
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)


   2. deepEqual
   ?   
  t.deepEqual(NaN, NaN, '?')
              |    |        
              NaN  NaN      
  
      Test.fn (test.js:8:4)
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by sindresorhus** [comment]
1. is correct as it's just `===`.
2. is just `===` for every property in the compared object.

This is just a quirk in JS. I don't think it's our job to fix that.

Same result with:

```
❯ node
> assert.deepEqual(NaN, NaN)
AssertionError: NaN deepEqual NaN
```

The correct way of checking for NaN is using:

```js
t.true(Number.isNaN(NaN));
```

**Comment by SergioMorchon** [comment]
@sindresorhus I don't think so.
One thing is that in runtime production code you don't anything operated with `NaN` to result other than a `NaN` value, too. Even `NaN` with itself, because it represent an indetermination. And by definition, you can not assure that one undefined value is the same undefined value.

But *in a test*, where you are *not operating with* values *but just comparing them*, and most importantly inside a `deepEqual`, it is really interesting get this handled.
In a test I just want to assert that some NaN value is effectively NaN.
Same happens with the Date object constructed with a NaN.

And because of this, here I have two options:

1. Change my production code to avoid `NaN`, something I really don't want to.

1. Don't use `deepEqual`, `is` etc. and handle the special case manually. Something unacceptable due to the complexity on the nested objects to test.

I would be pleased if Ava could handles this.

**Comment by sindresorhus** [comment]
@SergioMorchon This issue is old. `t.is()` handles NaN now. `t.deepEqual()` does not. Open a new issue about handling NaN in `t.deepEqual()`.

**Comment by novemberborn** [comment]
Actually both `t.is()` and `t.deepEqual()` consider `NaN` values to be equal now. `t.is()` uses [`Object.is()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is), and `t.deepEqual()` uses that same function to compare numbers.
