### ISSUE TITLE
Watch mode to print short time and which file changed

### ISSUE THREAD

**Issue by mightyiam** [avajs/ava#1194]
How about it by default?

**Comment by sindresorhus** [comment]
Not entirely clear what you're suggesting. Can you elaborate or show an example?

**Comment by mightyiam** [comment]
Well, I've experienced a bug somewhere in some stack before, where something that was supposed to be watching files, wasn't catching all changes. One such experience is enough for me to desire to have clear indication as to what file changed and when. Yet, this information should be concise and stay out of the way.

So, I would prefer a relative path of the file.

And, a stopwatch of the time since the change, in granularity of seconds. I'm not sure what terminal powers allow this. But, if a progress bar is possible then this should be, as well.

`6 seconds ago changed: lib/index.js` somewhere. Perhaps at the bottom. Perhaps with some colors.

And the stowatch is actually running, yes?

I think that this would make clear which file changed last and how long ago. So basically, when I hit save in my editor and look at the running watch, I can see that it did, indeed, re-run my tests.

**Comment by novemberborn** [comment]
> Well, I've experienced a bug somewhere in some stack before, where something that was supposed to be watching files, wasn't catching all changes. One such experience is enough for me to desire to have clear indication as to what file changed and when. Yet, this information should be concise and stay out of the way.

See the [documentation for debugging watch mode](https://github.com/avajs/ava/blob/master/docs/recipes/watch-mode.md#debugging).

Ordinarily this information is not required since the test output already shows you which files have rerun. Typically users shouldn't have to worry about why a particular test file ran. Sometimes watch mode is misconfigured, which is where the debug output comes in.

Closing, but if you tried debug mode and it didn't solve your problem feel free to keep discussing here.
