### ISSUE TITLE
Excluding files/folders in .gitignore from ava-files

### ISSUE THREAD

**Issue by transcranial** [avajs/ava#1229]
See #1228 for an example as to why this would be helpful.

**Comment by sindresorhus** [comment]
Just to add some description, this issue is about ignoring files matching glob patterns defined in `.gitignore` (not ignoring the .gitignore file itself). Ideally, the functionality would be added to [`globby`](https://github.com/sindresorhus/globby) as an option so it could benefit many other projects, but we would also consider adding it here if it's too hard to generalize.

**Comment by novemberborn** [comment]
It should still be possible to explicitly select files that are otherwise ignored through `.gitignore`.

**Comment by sindresorhus** [comment]
Globby now has a [`gitignore` option](https://github.com/sindresorhus/globby#gitignore).

**Comment by novemberborn** [comment]
> It should still be possible to explicitly select files that are otherwise ignored through `.gitignore`.

Does Globby take care of that? Otherwise overriding exclusion patterns is too difficult. But maybe we can support it as a configuration option.
