### ISSUE TITLE
Assigning `t.context` a value in `beforeEach` results in a Flow error

### ISSUE THREAD

**Issue by gajus** [avajs/ava#1340]
## Description

Assigning `t.context` a value in `beforeEach` results in a Flow error.

### Test Source

```js
// @flow

test.beforeEach(async (t) => {
  t.context = {};
});
```

### Error Message & Stack Trace

```
test/interceptors/cache/index.js:19
 19:   t.context = {};
       ^^^^^^^^^ assignment of property `context`. Property cannot be assigned on any member of intersection type
 19:   t.context = {};
       ^ intersection
  Member 1:
   83: type TestContext = AssertContext & {
                          ^^^^^^^^^^^^^ AssertContext. See: node_modules/ava/index.js.flow:83
  Error:
   19:   t.context = {};
           ^^^^^^^ property `context`. Property not found in
   83: type TestContext = AssertContext & {
                          ^^^^^^^^^^^^^ object type. See: node_modules/ava/index.js.flow:83
  Member 2:
   83: type TestContext = AssertContext & {
                                          ^ object type. See: node_modules/ava/index.js.flow:83
  Error:
   19:   t.context = {};
           ^^^^^^^ property `context`. Property not found in
   83: type TestContext = AssertContext & {
                                          ^ object type. See: node_modules/ava/index.js.flow:83
```

### Config

N/A

### Command-Line Arguments

N/A

## Environment

```
Node.js v7.7.1
darwin 16.5.0
0.18.2
4.1.2
```

**Comment by sindresorhus** [comment]
// @leebyron

**Comment by zs-zs** [comment]
I've just ran into the same issue while evaluating Flow. It seems the cause of the problem is that `beforeEach` and `afterEach` now has the type `TestMethod` which can only have a `Test` body instead of a `ContextualTest`. Changing its type to `ContextualTest` fixed the issue - at least for me.

But it's strange that there is one automated test which is actually asserting that context should *not* be there: https://github.com/avajs/ava/blob/master/test/flow-types/regression-1114.js.flow#L29

I checked the issue #1114 which doesn't seem to be relevant to the fact that `beforeEach` and `afterEach` has a context...? So I'm not sure if the failing test is the sign of something wrong or just the unit test is what needs to be revisited.

**Comment by novemberborn** [comment]
> I checked the issue #1114 which doesn't seem to be relevant to the fact that beforeEach and afterEach has a context...? So I'm not sure if the failing test is the sign of something wrong or just the unit test is what needs to be revisited.

I think the unit test is wrong, and indeed the type definition

**Comment by zs-zs** [comment]
Okay, I fixed the test by removing it :) Also did some cleanup. Let's see how it works.

Until the fix is released, a possible workaround is casting to any which seems to solve the problem:

```
test.beforeEach((t:any) => {
	t.context = new TestContext(); // no errors
});

test.afterEach.always((t:any) => {
       ...
});
```
