### ISSUE TITLE
--match incorrectly flags test as `.only`, making them unskippable

### ISSUE THREAD

**Issue by muyu66** [avajs/ava#1416]
I meet a question that i can't resolve using AVA

I build a.js file from a.ts using "tsc && ava".

It is source code:

```
import test from 'ava';

test.before(t => {
..........
});

test.skip('test1111', t => {
..........
});

test('test22222', t => {
...........
});
```

But, the code throw a exception :

```
TAP version 13
/home/zhouyu/Web/framework/node_modules/.0.19.1@ava/lib/runner.js:119
            throw new TypeError(validationError);
            ^

TypeError: `only` tests cannot be skipped
    at Runner.addTest (/home/zhouyu/Web/framework/node_modules/.0.19.1@ava/lib/runner.js:119:10)
    at Function.Runner.chain.optionChain (/home/zhouyu/Web/framework/node_modules/.0.19.1@ava/lib/runner.js:99:10)
I am confused that my 'test1111' test isn't a ''only' test.
```

This is my package.json :
```
  "ava": {
    "files": [
      "build/test/*.js"
    ],
    "source": [
      "**/*.{js}"
    ],
    "match": [
      "*"
    ],
    "failFast": false,
    "tap": true
  }
```

My ava version is : **"ava": "^0.19.1"**

This is my usage problem, or, AVA bug?

Help me, thanks.

**Comment by ORESoftware** [comment]
interesting

**Comment by novemberborn** [comment]
The problem is the `match` option. Note that with `*` it doesn't need to be set, since it'll match anything.

The way `match` is implemented is we mark a test as `exclusive` when it matches: https://github.com/avajs/ava/blob/212b5de5759fdb267d837620c3eec7e5695a23e1/lib/runner.js#L114

Unfortunately we do the same when `test.only()` is used! We should set an additional property that tracks whether the test is exclusive because of `test.only()` or `--match`, and make `.skip()` only throw on `test.only()`.
