### ISSUE TITLE
The current Vue recipe is very slow (4X slower than other frameworks)

### ISSUE THREAD

**Issue by eddyerburgh** [avajs/ava#1510]
## Description

The current [Vue recipe is very slow](https://github.com/avajs/ava/blob/master/docs/recipes/vue.md). This makes it [more than 4x slower than Jest or mocha-webpack](https://github.com/eddyerburgh/vue-unit-test-perf-comparrison).

I believe this is because it doesn't cache compiled .vue files.

I'm going to investigate, and am happy to PR an improved recipe. Just wanted to make this public in case other people are working on it.

I would appreciate any pointers in the right direction 🙂. 

### Config

Copied from the recipe.

## Relevant Links

- https://github.com/eddyerburgh/vue-unit-test-perf-comparrison/tree/master/ava

## Environment

darwin 16.7.0
ava 0.22.0
node 8.4.0
npm 5.3.0

**Comment by jackmellis** [comment]
Yes I've been thinking about this for a while now. Because Ava starts so many new processes, in-memory caching becomes redundant. I feel this is where the performance is hitting (that and the sheer size of babel-core) I think a possible solution would be to add some persisted caching to the core require-extension-hooks module, so unchanged files are not transpiled over and over. I've not had time to implement it yet though.
