### ISSUE TITLE
ava does not bubble up "verbose" option to nyc output

### ISSUE THREAD

**Issue by niftylettuce** [avajs/ava#1519]

**Comment by niftylettuce** [comment]
if you have something like a TypeError, the actual output will not bubble up to nyc so it will look like:

<img width="609" alt="screen shot 2017-09-15 at 5 36 30 am" src="https://user-images.githubusercontent.com/523141/30476650-a9eff77c-99d8-11e7-8c60-6df01f2505c3.png">

versus:

<img width="606" alt="screen shot 2017-09-15 at 5 37 22 am" src="https://user-images.githubusercontent.com/523141/30476662-b089a0e2-99d8-11e7-9e70-4d8100d7f45f.png">

**Comment by niftylettuce** [comment]
fyi this is run with `nyc ava`, and I have tried both `nyc ava --verbose` and also a block in package.json for ava such as `"ava": { "verbose": true }`

**Comment by novemberborn** [comment]
The verbose reporter prints each test, even when successful. I don't think that's the issue here. It looks like when you run AVA through nyc the highlighted line contents aren't shown. That's quite odd, especially since the surrounding lines are displayed.

Could you try `nyc ava --no-color` (or perhaps it needs to be `nyc ava -- --no-color`)? That'll disable the color output.

**Comment by niftylettuce** [comment]
None of that works @novemberborn - it simply does not work with nyc.  I've tried no-color and your other variation as well.

**Comment by niftylettuce** [comment]
It's highlighting the wrong line and not showing the proper output.

**Comment by novemberborn** [comment]
@niftylettuce would you be able to share your project? Or make a reproduction that is shareable? I don't know why this would be happening so I'm afraid I can't be of assistance without reproducing the issue locally.
