### ISSUE TITLE
tap-diff fail shows undefined/undefined

### ISSUE THREAD

**Issue by scottnath** [avajs/ava#1573]
## Description

When using `tap-diff` as a reporter, actual difference is not shown, instead it just says `undefined undefined`.

### Test Source

This is available to test online here: https://glitch.com/edit/#!/ava-example

The above glitch (glitch allows a code playground for node) has a very basic ava setup with a very basic test:

```js
import test from 'ava';

test('show diff', t => {
  t.pass('good job');
  t.is('one', 'two', 'one is not two');
});
```

### Error Message & Stack Trace

```bash
$ npm run ava
> my-glitch-app@0.0.1 ava /app
> ava --tap | tap-diff
  show diff
    ✖  show diff at Test.t [as fn] (tests/test.js:5:5)
        undefinedundefined
passed: 0  failed: 1  of 1 tests  (3s)
1 of 1 tests failed.
```

![screen shot 2017-10-27 at 12 42 41 pm](https://user-images.githubusercontent.com/216931/32115394-a7c1b5e6-bb14-11e7-907c-5d96bcc3fd39.png)

### Config

[see package.json](https://glitch.com/edit/#!/ava-example?path=package.json:4:69)
relevant section from `package.json`:

```json
{
  "ava": {
    "files": [
      "tests/*.js"
    ],
    "failFast": false,
    "tap": true
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
npm runava
```

## Relevant Links

This is available to test online here: https://glitch.com/edit/#!/ava-example

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v8.4.0
darwin 16.7.0
$ npm --version
3.10.10
$ ava --version
0.23.0
    "tap-diff": "^0.1.1"
```

thank you!

**Comment by novemberborn** [comment]
Our TAP reporter doesn't really include the information I guess `tap-diff` relies on. I'm not even sure if there's a spec on *how* that should be included, especially for values that aren't easily serialized to JSON.

AVA's regular reporters do show diffs. I recommend you use those, but I appreciate that might not help if you have a workflow that depends on TAP.

(I'm closing this issue since I don't think there's anything AVA can do here, at least at this point. Please feel free to continue the discussion.)
