### ISSUE TITLE
Feature request for testing object keys

### ISSUE THREAD

**Issue by cyberwombat** [avajs/ava#1600]
## Description

I do quite a bit of testing on APIs where I want to ensure the returned object contains exactly the correct keys but I am not interested so much in their value especially as a lot of it is autogenerated.

I've used Chai's [keys](http://chaijs.com/api/bdd/#method_keys) for this. Currently in AVA I have to do:

    t.deepEqual(Object.keys(response).sort(), ['bar', 'foo'])

This is awkward especially since I have to make sure to alphabetically sort my matching array.

Is there an interest in adding such a feature? Perhaps there is a better way to do this than I am doing now though.

**Comment by vadimdemedes** [comment]
I don't think it should be in the core, since it's easy to do what you're suggesting without AVA's involvement:

```js
const keys = obj => Object.keys(obj || {}).sort()

t.deepEqual(keys(response), ['foo', 'bar'].sort())
```

If we would add it to AVA, it'd most probably have a long name like `t.deepEqualKeys` and we'd have to add a `t.not*` method for it as well. This doesn't sound like something we would want, I think.

**Comment by novemberborn** [comment]
As @vadimdemedes said, we're not looking to add highly specific assertions like these. A helper method is a good approach.

(Closing to keep the issue list nice and tidy, but please feel free to continue the conversation.)
