### ISSUE TITLE
Tests execution benchmarks (time statistic)

### ISSUE THREAD

**Issue by MaxVinogradov** [avajs/ava#1606]
### Problem description:
Could you please advice any TAP reporter or anything else,  that show tests benchmarks (time statistic) correctly.
For example now I use *tap-spec*, and when I run all tests this reporter print:
```
...
✔  Super Test should have good result implementation [pass: 1, fail: 0, duration: *0ms*]
...
```
but when I run only one, target test I have next result (and it's more correctly):
`✔  Super Test should have good result implementation [pass: 1, fail: 0, duration: *36ms*]`

### Versions:

- "ava": "^0.24.0",
- "tap-spec": "^4.1.1"

**Comment by novemberborn** [comment]
AVA doesn't output test duration in the TAP reporter. Best I can tell this comes from `tap-spec` itself: https://github.com/scottcorgan/tap-spec/blob/8ce610dc87cfe81764f411ed7f980577298f7885/index.js#L122

Generally speaking we'd rather not track duration for individual tests, since by default tests run concurrently. The results wouldn't be particularly accurate.

(Closing this since we won't be changing the current behavior, but please feel free to continue the conversation.)
