### ISSUE TITLE
100% coverage

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#161]
We're currently at 96% coverage. Which is amazing. Getting us closer to 100% would be a good beginner task. 

**Please leave this for first time contributors.**

See https://coveralls.io/github/avajs/ava?branch=master for uncovered code.

**Comment by alejandronanez** [comment]
@sindresorhus your link is outdated. This should be the right one: https://coveralls.io/github/avajs/ava?branch=master

**Comment by EEtancelin** [comment]
Fine, i dev beginner and i will be happy to take à look and see how improve code coverage.

**Comment by platy11** [comment]
@sindresorhus I was looking at [cli.js100](https://github.com/avajs/ava/blob/master/lib/cli.js#L100) and in my testing (in your `cat-names` repo) I cannot get the deprecation error to appear - is this just me?

**Comment by novemberborn** [comment]
@platy11 that line is in `master` but not yet in a release.

**Comment by platy11** [comment]
@novemberborn Ok, thanks! :smiley:

**Comment by wildaces215** [comment]
Where can I start writing tests for ava it seems like a good place to start contributing to open source software!

**Comment by novemberborn** [comment]
@wildaces215 you can browse our current code coverage at https://codecov.io/gh/avajs/ava. Look for a file that has little coverage, try and figure out what it does, and see if you can write a test that extends the coverage.

We'd be interested in covering larger pieces of logic rather than small edge cases.
