### ISSUE TITLE
Disable logging of `t.context`

### ISSUE THREAD

**Issue by pvdlg** [avajs/ava#1611]
The `t.context` is really convenient in a lot of situations. I use it primarily to:
- Set up some stubs, so each test will have it's own freshly created stub
- Import the module I'm testing with [proxyquire](https://github.com/thlorenz/proxyquire) passing the stubs

When a test fail, the entirety of `t.context` is logged, which is several hundred lines just for a [sinon stub](http://sinonjs.org/releases/v4.1.3/stubs/). The information stored in the `t.context`, at least in my case, is not really useful to find the reason of the failure and make it harder to find the relevant logs provided by the assertion.

In addition, storing sensitive information in the `t.context` (like environment variables) present a security risk as those information will be exposed in the logs in case of a failed test. It's up to the user to not do something that could expose those information, but it's not immediately clear that anything in `t.context` might be ends up in the logs.

Is there a particular reason for logging the content of `t.context`? Should we disable it? Or add an option to disable it?

**Comment by jamestalmage** [comment]
First, I want to make sure you've checked out [this podcast](https://www.briefs.fm/3-minutes-with-kent/27) by @kentcdodds. I find myself using `beforeEach` and friends very rarely any more. I'd almost call it an anti-pattern.

Secondly, a trivial test I set up, does not cause the behavior you are describing:

```js
test.beforeEach(t => {
     t.context.foo = 'foo';
});

test('foo', t => t.fail());
```

We are going to need to see a minimal reproducible example in order to help point you in the right direction. I'm fairly certain we aren't logging the context on test failure, but that you are somehow getting a reference to it in an object you are passing an assertion.

That's entirely possible with code like this:

```js
test.beforeEach(t => {
  t.context.mySpy = sinon.spy();
});

test('foo', t => {
  t.context.mySpy('blah', 'blah');  // context captured here
});
```

In the above example, sinon will capture and store a reference to `t.context`, because `t.context` is the execution context for that spy, and is necessary for the `spy.calledOn` assertion.

You could solve that with destructuring:

```js
test('foo', t => {
  const {mySpy} = t.context
  mySpy('blah', 'blah'); // mySpay `this` reference is undefined now
});
```

**Comment by pvdlg** [comment]
Thanks for the very fast answer! And the podcast!

What you described is exactly what I'm doing and what I observe as a result!
Indeed destructuring my stub out of the `t.context`, prevent to log the rest of the `t.context`.

I'm closing, as there is no issue. Thanks again!
