### ISSUE TITLE
Clear Terminal Screen When Running In Watch Mode

### ISSUE THREAD

**Issue by clemtrek** [avajs/ava#1623]
## FEATURE

It would be nice to clear terminal screen while running in watch mode.

A Simple package like [clear](https://github.com/bahamas10/node-clear) could be used.

## WHY ?

It becomes very disturbing when running tests in watch mode and the terminal gets filled very quickly,
So you have to clear it manually.

**Comment by novemberborn** [comment]
The previous run is left visible since you may need to refer back to it while you're debugging test failures. Admittedly the larger the test suite the more confusing this gets. We do try to print a separator so you know where the previous run ended.

Most terminals have a shortcut for clearing the screen. I often use this, followed by typing <kbd>r</kbd> + <kbd>Enter</kbd> which reruns the tests for you.

We're open for suggestions on how to improve the separation between the test runs. Or perhaps we should have a "clear and rerun tests" command?

**Comment by clemtrek** [comment]
@novemberborn , Is there a way to run only the changed tests in watch mode so that all tests are not run again ?

This could make it comfortable on the console.

**Comment by novemberborn** [comment]
@clemtrek watch mode does that automatically when you modify files.

**Comment by clemtrek** [comment]
Thanks

**Comment by novemberborn** [comment]
@capttrousers I think the right approach is to improve the reporters, see #2500.
