### ISSUE TITLE
Allow tests to take stdin from the master test process

### ISSUE THREAD

**Issue by jviotti** [avajs/ava#1682]
## Description

We have a use case where we need some end to end tests to take stdin input (key strokes) from the user before doing some assertions (the test waits for some human input intervention). In particular, we have test suite that performs hardware tests on a board. Some tests are hard to automate (ie LED blinks), so before investing in more advanced technology, we decided to prompt the user to check certain things. In the case of LEDs, the test case will start blinking the LED for like 5 seconds, and ask the user if he can confirm it worked.

We noticed that if we use something like Inquirer.js, the parent Ava process that receives the key strokes will not forward them to the child test processes, as the `silent: true` option from `child_process.fork()` is set.

I understand that this might not make sense given that Ava spawns test processes in parallel, and therefore key strokes sent to the master process might be piped to more than one test at the same time, so what about piping stdin to the child's stdin if `serial: true`? 

We have a small patch that pipes stdio and makes it all work for us:

```diff
diff --git a/lib/fork.js b/lib/fork.js
index 0ca0f45..655ed8f 100644
--- a/lib/fork.js
+++ b/lib/fork.js
@@ -43,6 +43,10 @@ module.exports = (file, opts, execArgv) => {
                execArgv: execArgv || process.execArgv
        });

+       if (opts.serial) {
+         process.stdin.pipe(ps.stdin);
+       }
+
        const relFile = path.relative('.', file);

        let exiting = false;
```

What do you think?

### Test Source

```js
const ava = require('ava')
const inquirer = require('inquirer')

ava.test('should pass', (test) => {
  return inquirer.prompt([
    {
      type: 'confirm',
      name: 'result',
      message: 'Did the test pass?',
      default: false
    }
  ]).then((answer) => {
    test.true(answer.result)
  })
})
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "verbose": true,
    "serial": true
  }
}
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

- Node.js v6.1.0
- darwin 17.4.0

**Comment by novemberborn** [comment]
@jviotti this is a very interesting use case. Typically our response is that you should wrap the invocation of AVA in some other script.

You're right that stdin forwarding would work in `--serial` mode, but it wouldn't work in watch mode. There's just too many ways in which users may expect to use AVA that your proposal is not compatible with.

Note that you could write a wrapper script that uses Inquirer. If you then load `ava/cli` it should behave the same as if you invoked `ava` directly.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by sindresorhus** [comment]
Inquirer can easily be mocked, which would be a better way to test it. Alternatively, spawn a separate file and check the output.

**Comment by novemberborn** [comment]
> Inquirer can easily be mocked, which would be a better way to test it. Alternatively, spawn a separate file and check the output.

The issue seems to be that test success depends on hardware state. It's not that Inquirer can't be mocked, it's that @jviotti requires actual user input before the tests continue.

**Comment by jviotti** [comment]
@novemberborn Thanks for the response!

> Note that you could write a wrapper script that uses Inquirer. If you then load ava/cli it should behave the same as if you invoked ava directly.

Not sure I get it. `ava/cli` is CLI entry point of this library, right? Can you elaborate on how wrapping such same entry point would make a difference? I guess I can execute Inquirer.js on the wrapper script, but how would the wrapper script pass the response back to the running Ava tests?

**Comment by novemberborn** [comment]
@jviotti ah apologies, I overlooked that you wanted the user to confirm whether the test passed. That is trickier to do with wrapper scripts. Regardless I think it's not a use case we should support with AVA.

An outline of how you could make this work:

* Write a companion script that starts a server (either HTTP or unix domain socket)
* Run the tests
* In the test, send a request to the companion server
* In the companion server, ask for user input
* Send the input back to the test and run an assertion

**Comment by jviotti** [comment]
No worries! I was able to get it working with a wrapper script + IPC between the wrapper and the children.

**Comment by ianwalter** [comment]
Very recently I created [webdriver-helper](https://github.com/ianwalter/webdriver-helper), a simple AVA helper to provide a [WebdriverIO](https://webdriver.io/) browser instance in a test. It works well, and I prefer writing AVA tests instead of using Mocha or Jasmine (which WebdriverIO officially integrates with), but one issue is that `await browser.debug` doesn't work properly. [`browser.debug`](https://webdriver.io/docs/debugging.html#the-debug-command) is cool because it provides a REPL interface to WebdriverIO that lets you enter commands and try to figure out why your test isn't working as expected. Commands being typed in aren't making it to WebdriverIO though and I don't really understand how or why.

> There's just too many ways in which users may expect to use AVA that your proposal is not compatible with.

I feel like my use case is different in that a proposed interface could be made available through a manual process and not by default? I don't know what the proposed interface looks like but the discussed workaround seems very complicated so I'm asking that this feature be reconsidered.

**Comment by novemberborn** [comment]
@ianwalter the work in https://github.com/avajs/ava/pull/2011 would let you run tests in the main process, and there you'd have access to `stdin`. Would be great to see some experiments with that before adding any additional features to AVA itself.

I can't give you a timeline on when that's ready (mostly because I'm busy with work and it's a large PR) but perhaps you could give the in-progress branch a go?

**Comment by ianwalter** [comment]
@novemberborn Absolutely, will try it out, thanks for your help.
