### ISSUE TITLE
test.only() not working when config in ava section contains match items

### ISSUE THREAD

**Issue by qaiser110** [avajs/ava#1782]
Having **test.only()** on tests does not work and is completely ignored when ava config in `package.json` contains `match` items.

For instance, I have multiple tests with only one `test.only()` 

I run tests with this command:

```sh
ava --only
```

I have this config:

```json
"ava": {
    "files": [
      "tests/**/*.js"
    ],
    "sources": [
      "common/**/*.{js,json}",
      "!dist/**/*"
    ],
    "match": [
      "!*skip*"
    ]
```

**Expected Behavior:**

Only the test with `.only()` flag should run.

**Actual Behavior:**

All tests run, ignoring the `.only()` flag.

**Current Workaround:**

Remove the `match` items, like this: 

```json
"match": []
```
When `match` items are removed, only the test with `.only()` flag is run, as expected.

**Environment:**

- ava 1.0.0-beta.4
- Node.js v9.11.1
- npm 5.6.0
- darwin 17.2.0

**Comment by novemberborn** [comment]
This is the [expected behavior](https://github.com/avajs/ava/#running-tests-with-matching-titles).

Both `--match` and `.only()` are ways to refine what tests run, typically used during development. I suppose it could be argued that when both are used, AVA should exclusively run `.only()` tests with matching titles, but I'm not sure how useful that would actually be.

Going by your config you seem to be annotating tests you don't want to run by putting "skip" in their titles. Did you see AVA has `test.skip()` which does the same thing, but without using `--match`?

P.S. there currently is no `--only` option.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

- [ ]

**Comment by qaiser110** [comment]
Thanks @novemberborn
