### ISSUE TITLE
snapshots are in binary, any way to store in raw text?

### ISSUE THREAD

**Issue by capaj** [avajs/ava#1806]
is there any way to save snapshots in UTF8 text form rather than like this?

![image](https://user-images.githubusercontent.com/1305378/40249816-7b62450a-5ad4-11e8-8d73-f53d98039022.png)

**Comment by novemberborn** [comment]
The underlying serialization is not meant to be readable, editable or diffable. It has a binary encoding. What you see here is a GZip compression of all serializations.

Why are you concerned about the format?

I suppose we could write Base64 to the file but I don't think that adds any value.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by novemberborn** [comment]
Did you see the Markdown files AVA generates? They’re the ones meant for us humans :smile:

**Comment by iamstarkov** [comment]
@novemberborn how hard is it to support non-binary shapshots?

**Comment by novemberborn** [comment]
@iamstarkov why are you concerned about the format?

**Comment by iamstarkov** [comment]
@novemberborn it drives people away from Ava to jest in my company =(

**Comment by novemberborn** [comment]
@iamstarkov do you know what in particular they don’t like?

**Comment by iamstarkov** [comment]
@novemberborn they are accustomed to jest snapshots and have routines based on text-based snapshots, so they are don't understand why Ava needs snapshots to be binary and quite unhappy about it

**Comment by bailer** [comment]
To fill in for @iamstarkov: Coming from Jest, the feature I miss the most is the interactive mode that Jest has. It really makes updating one snapshot at a time a breeze though that has nothing to do with storing the snapshot as a binary. 

Though a problem I found with binary snapshots is when you update a snapshot in two different branches which comes from the same origin branch. Git can diff and merge the markdown files fine but there is always a merge conflict with the binary. What is your thoughts on this?

**Comment by novemberborn** [comment]
> Coming from Jest, the feature I miss the most is the interactive mode that Jest has. It really makes updating one snapshot at a time a breeze though that has nothing to do with storing the snapshot as a binary.

That sounds like a nice feature to have!

> a problem I found with binary snapshots is when you update a snapshot in two different branches which comes from the same origin branch. Git can diff and merge the markdown files fine but there is always a merge conflict with the binary. What is your thoughts on this?

Interesting. I haven't run into that but that's probably more due to the kind of projects I work on. A [custom merge driver](https://www.npmjs.com/package/npm-merge-driver) which re-runs the appropriate tests may be a solution.

How often do you run into this where the Markdown file also conflicts? Or, if you can recall, where Jest snapshot files had such conflicts?

**Comment by ericwooley** [comment]
Since this was closed, I assume there is no way to switch to text based then? I don't see anything in the docs


Here is my reasons for preferring raw output:
1. Git itself is much better at storing text than binary.
2. Diffs of outputs are much easier to verify. In a PR I have to basically break the test to see what is different, huge PITA. With raw text, I can just see, in a diff or PR, `expected output old` has been updated to `expected output new`
3. I don't see any benefits to storing in binary besides a very small amount of disk savings?
4. I can't simply open the snapshots with a standard editor and view them.

**Comment by novemberborn** [comment]
@ericwooley AVA outputs both Markdown and binary files. The Markdown files are for us humans, including in PR reviews. The binary files are what enables AVA do to structured and colored diffs when the snapshot differs.

**Comment by novemberborn** [comment]
@turadg The level of detail contained in the binary data wouldn't be very readable or editable in JSON, either. I do that snapshots shouldn't just be edited, in my view the source of truth is what your test recorded.

Inline snapshots are interesting but a few steps beyond what we can support in AVA, snapshot format aside.

I suspect we could implement an adapter for the Jest API.
