### ISSUE TITLE
Source map weirdness when using `@babel/register`.

### ISSUE THREAD

**Issue by ronen** [avajs/ava#1899]
Somewhat of a followup to #1882.  That issue -- path for the reported filename when an exception is thrown in a test file, when using `@babel/register` to compile sources -- has been fixed (thanks!).  This issue regards reporting the source code line number & snippet in that circumstance.

I can get two different weirdness, depending on configuration:

1. Don't compile test files:  reported line number is last line of the file, no code snippet is shown.

    The doc at https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#compile-sources says "`@babel/register` will *also* process your test and helper files. For most use cases this is unnecessary".  But even with a trivial use case, if as suggested there I configure `@babel/register` to ignore test files, then the report shows the incorrect line number for the exception, and does not include the code snippet.  I don't know whether the doc is simply giving incorrect advice, or whether the doc should be right but there's a bug. 

2. Compile test files:  The reported line number is off by one, code snippet is shown at that wrong line.

(I don't know whether these are two symptoms of a single issue or two different issues, but seems best to report them together.)

### Test Source

Here is `test/test-file.js`

```js
import test from 'ava'

import '../src/dummy'

test('test-name', t => {
  "foo".bar() // throws a TypeError
})
```

`../src/dummy.js` can be completely empty.

### Error Message & Stack Trace

For the two cases...

1. With `@babel/register` required but configured to ignore `test/*`, the  reporter lists the wrong line for the exception, and doesn't include the code snippet:

    ```
    1 test failed

    test-name

    /Users/ronen/test/ava-issue/test/test-file.js:10      <====== but the file only has 7 lines!
                                                          <====== no code snippet :(
    Error thrown in test:

    TypeError {
      message: '"foo".bar is not a function',
    }
    ```

    If you comment out the line `import '../src/dummy'` in the test file, then this works properly:

    ```
    1 test failed

    test-name

    /Users/ronen/test/ava-issue/test/test-file.js:6

     5: test('test-name', t => {
     6:   "foo".bar() // throws a TypeError      <====== [this line is highlighted, as expected]
     7: })

    Error thrown in test:

    TypeError {
      message: '"foo".bar is not a function',
    }
    ```

2. With `@babel/register` compiling test files, the reporter lists the wrong line for the exception, though it does include the code snippet:

    ```
    1 test failed

    test-name

    /Users/ronen/test/ava-issue/test/test-file.js:5      <====== but the exception is on line 6!

     4:
     5: test('test-name', t => {                         <====== [this line is highlighted]
     6:   "foo".bar() // throws a TypeError

    Error thrown in test:

    TypeError {
      message: '"foo".bar is not a function',
    }
    ```

    This happens whether or not `../src/dummy` is imported.

### Config

Two cases...

1. Ignoring test files.  Here is `package.json` in its entirety:

    ```json
    {
      "ava": {
        "require": [
          "./test/_register.js"
        ]
      },
      "devDependencies": {
        "@babel/register": "^7.0.0-beta.56",
        "ava": "^1.0.0-beta.7"
      }
    }
    ```

    and `test/_register.js`:

    ```js
    require('@babel/register')({
      // These patterns are relative to the project directory (where the `package.json` file lives):
      ignore: ['node_modules/*', 'test/*']
    })
    ```

2. Compiling test files.  Use the same config as case 1, but change the `ava` stanza to directly require `@babel/register` instead of `./test/_register.js`, or change `_register.js` to have `ignore: ['node_modules/*']` -- same results either way.

### Command-Line Arguments

No command line arguments.  Just

```
npx ava
```

## Relevant Links

Minimal reproduction here: https://github.com/ronen/ava-filepath-issue -- this is configured for case 1  (not compiling test files), tweak the config to get case 2.

## Environment

```
$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v10.8.0
darwin 17.7.0
$ npx ava --version
1.0.0-beta.7
$ npm --version
6.3.0
```

**Comment by novemberborn** [comment]
Thanks once more for the detailed report @ronen.

I think in case two this is an issue of Babel miscomputing the source map, and / or the source map conversion of the stack trace not mapping back correctly. It might be out of our hands.

With the first case you may be bumping into https://github.com/avajs/ava/issues/974 — where `@babel/register` prevents our source map conversion from working.

This all needs a bit more digging so I'll leave this open as a `question` for now.

**Comment by novemberborn** [comment]
Right! So, AVA installs `source-map-support` first. However this module only guards against repeated installations if the same version is used, see https://github.com/evanw/node-source-map-support/issues/200. `@babel/register` uses `^0.4.2` which selects `0.4.8`, whereas AVA uses `0.5.9`.

Consequently in the first scenario, `@babel/register` replaces AVA's installation, which means source maps for the test file are not applied. Of course if the error is thrown in any code compiled through `@babel/register` it'd be fine.

In the second scenario it may just be that `@babel/register` pulls in an outdated `source-map-support`, which itself pulls in an outdated `source-map` (`^0.5.3` rather than `^0.6.0`). All these non-SemVer releases don't help either.

Ultimately, if we can get rid of `source-map-support` we'd have a better chance of dealing with this mess. That's what #974 is about. Of course the tricky bit would be how to handle files compiled outside of AVA, without `@babel/register`, but perhaps we can suggest users to require `source-map-support/register` themselves.

I'll also try and nudge the related packages to update their dependencies and switch to SemVer releases, so that package deduplication reduces these conflicts.

Of course at *that* point AVA's `source-map-support` would no longer be overwritten by `@babel/register` and we'll still have incorrect output. But that's what #974 is for 😉 

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by ronen** [comment]
> I'm closing this issue for housekeeping purposes

...yes this source map stuff seems like quite a messy tangle, housekeeping is a good idea :)  

Thanks for looking into it and for the update.  I'll keep my eye on #974
