### ISSUE TITLE
Provide useful feedback when using t.throws() with async functions

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1932]
As of [1.0.0 beta 7](https://github.com/avajs/ava/releases/tag/v1.0.0-beta.7), `t.throws()` only works with synchronous functions. We should detect when it's used with a promise and provide useful feedback. I also think we should add a no-op `.catch()` handler to the promise to prevent AVA from logging an unhandled rejection.

See: https://github.com/avajs/ava/blob/bfe16300e07c12a1bad2e4f02898b1e7486daf70/lib/assert.js#L341 and compare with: https://github.com/avajs/ava/blob/bfe16300e07c12a1bad2e4f02898b1e7486daf70/lib/assert.js#L365

Thanks to @Lukenickerson for raising this in #1931.

**Comment by grant37** [comment]
I'd like to work on this if that's alright. Messing around locally and trying to follow the guidelines here I had success (I think) with: 
1. Checking if the `fn` argument to `throws()` returns a promise (and adding the no-op catch here)
2. If it does, calling `fail()` like it's called on line 314 with a message about asynch functions
3. Wrapping all this in a try/catch (no-op) because I got errors on the promise check if `fn` was synchronous (probably there's a better method though?)

The result is a test failed message that refers to the line `await t.throws(asynch () => {` in a test file (from #1931), which is all I tested against so far. Would this be the correct behavior/do you see any issues?

**Comment by novemberborn** [comment]
@grant37 sounds like you're nearly there! Please make the PR and we can get it in.
