### ISSUE TITLE
Typescript with module resolution "esnext" not working

### ISSUE THREAD

**Issue by nkint** [avajs/ava#1951]
Hi!
I'm new to AVA but I like to use it with typescript.
I really like it so far but:

## Description

Seems to me that writing test in typescript is currently broken with `"module": "esnext",` in the tsconfig:

```
(function (exports, require, module, __filename, __dirname) { import test from 'ava';
                                                                ^^^^^^

  SyntaxError: Unexpected token import
```

For the complete example you can see my example:
https://github.com/nkint/radial-label-placement

```
    "ava": "^1.0.0-beta.8",
    "ts-node": "^7.0.1",
    "typescript": "^3.1.3"
```

I need `"module": "esnext",` because of I'm using https://github.com/developit/microbundle that requires it.

With  `"module": "commonjs",` AVA works correctly, but microbundle does not!

Can anyone help me?

**Comment by novemberborn** [comment]
TypeScript isn't transpiling ES Modules, and out of the box Node.js doesn't support ESM. I'd combine this with `esm`, see our recipe: https://github.com/avajs/ava/blob/master/docs/recipes/es-modules.md

Since you're not using Babel all you have to do is install `esm` and add it to the `require` config.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
