### ISSUE TITLE
yet another high severity vulnerability in the nested deps

### ISSUE THREAD

**Issue by a-x-** [avajs/ava#2182]
ava -> update-notifier -> ... -> deep-extend

[CVE](https://nvd.nist.gov/vuln/detail/CVE-2018-3750)

Update please the `update-notifier`

![Screenshot 2019-07-10 at 13 16 53](https://user-images.githubusercontent.com/6201068/60961517-0d0b5d00-a315-11e9-88fb-368fd8ed3268.png)

**Comment by novemberborn** [comment]
Presumably however deep this dependency is installed, given that the fix is in a patch release it will be pulled in when you re-install your dependencies. But also, given that this is not a direct dependency of AVA, and not even a direct dependency of `update-notifier`, there is nothing we can do about this here. And finally, given that both AVA and `update-notifier` run during *development* rather than in your server, the kind of vulnerability described here simply will not affect you.

Assessing vulnerability reports is not easy, but there's no need to open these kinds of issues.

**Comment by a-x-** [comment]
you can pin specific version into package-lock.json
