### ISSUE TITLE
Glob does not work.  **/*.test.ts does not exist.

### ISSUE THREAD

**Issue by SephReed** [avajs/ava#2489]
This is either a bug, or could use some better error messaging.  Looks like a decent glob to me.

> $ ava **/*.test.ts

**Comment by SephReed** [comment]
This is what works:
```
$ ava src/**/**/**/*.test.ts src/**/**/*.test.ts
```

any more or less `/**` and it'll fail

**Comment by novemberborn** [comment]
Yes that seems weird.

Could you share your AVA version, what shell you use, and a redacted directory layout?

**Comment by KSR-Yasuda** [comment]
If Linux, isn't it just shell completing the wild card beforehand, instead of ava?

How is `ava "**/*.test.ts"` to pass the pattern itself to ava?

**Comment by SephReed** [comment]
I'm on MacOS and had just `npm i ava`.  The directory layout is private, so I can't share it... but it's a bunch of folders, some have `__tests` folders..

Sorry I can't give more that that.

This is working for now.

**Comment by novemberborn** [comment]
The way this is supposed to work, AVA looks at the `files` configuration and finds all test files.

Then it looks at the CLI arguments, expands globs if necessary, and filters the test files accordingly. If this does not result in any files the error message is confusing, but see https://github.com/avajs/ava/issues/2373.

`**/*.test.ts` should match any `.test.ts` files that are run when you just invoke `npx ava`, even if your shell expands it.

I don't think this issue is actionable at this point, so I'll close it.
