### ISSUE TITLE
TypeScript instructions don't work?

### ISSUE THREAD

**Issue by ianstormtaylor** [avajs/ava#2693]
Based on the TypeScript instructions getting AVA working with TypeScript at runtime should be just installing `ts-node` and `typescript` and then adding configuration:

```ts
"extensions": [
  "ts",
  "tsx"
],
"require": [
  "ts-node/register"
]
```

But this results in errors for the `import` syntax:

```
Uncaught exception in test/ava/test.ts

/Users/Storm/dev/ianstormtaylor/nucleus/test/ava/test.ts:1
import test from 'ava';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Might there need to be more done as part of the configuration that isn't documented?

**Comment by fregante** [comment]
As far as I know, TypeScript + ESM support is not here yet. `ts-node` should support ESM via `ts-node/esm` as described here: https://github.com/TypeStrong/ts-node/issues/935#issuecomment-769608744

… but I don't see how to use that `--loader` node flag because AVA’s `require` option obviously tries to `require` that and it fails with:

```
  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./node_modules/ts-node/esm.mjs
```

**Comment by novemberborn** [comment]
@ianstormtaylor #2593 provides the solution, somebody just needs to turn it into a PR.

Alternatively if you want to avoid `ts-node`, https://github.com/avajs/typescript/issues/5 is about updating our TypeScript provider to support ESM.
