### ISSUE TITLE
Magic assert doesn't seem to work with "type": "module"

### ISSUE THREAD

**Issue by Filyus** [avajs/ava#2719]
Just add `"type": "module"` to **package.json** and run the failing test in ES-module, you don't see any code in the logs. I don't want to install something like Babel.
ava 3.15.0
Node 12.20.0

test.js:
```js
import test from 'ava';
test("test magic assert", t => {
  t.is(1, 2); 
});
```
log:
```
  test magic assert

  Difference:

  - 1
  + 2

  » file:///test.js:3:5

  ─

  1 test failed
```

Related: https://github.com/avajs/ava/issues/2293

**Comment by novemberborn** [comment]
It strikes me that the path is `file:///test.js` which implies the test file was at your file system's root. That seems odd. Assuming the file does not actually live there, this is probably the error.

I haven't had a chance yet to try and reproduce this but it's on my radar.

**Comment by novemberborn** [comment]
I suspect the problem is here: https://github.com/avajs/ava/blob/b8f5685ed5b828de884d0d72c988efe837058692/lib/serialize-error.js#L25-L34

I haven't tested it directly, but this came up in my work for #2741.

**Comment by jiby-gh** [comment]
@novemberborn not sure if it is fixed by #2741. I encountered the same issue today and tried with the master branch. The issue is still reproducible. Same setup as @Filyus, `"type": "module"` in package.json and everything as es modules.
![image](https://user-images.githubusercontent.com/52130524/128309099-48bb7514-a335-42ed-9460-7f8007e51fbb.png)

**Comment by jiby-gh** [comment]
hmm maybe it's because of the source maps, the files are compiled from typescript and the source maps point to `.ts` files.

![image](https://user-images.githubusercontent.com/52130524/128311584-0f918feb-b081-414b-820a-8d77e9faccfd.png)

**Comment by jiby-gh** [comment]
well, forgive my ignorance @novemberborn. Just found out that I would need additional configuration to work with precompiled typescript.

**Comment by jiby-gh** [comment]
unfortunately, es modules do not work with the `@ava/typescript` yet. 

I was curious though. My setup has IDE watchers that auto compile the typescript to javascript in the same folder on change. This was a nice setup for me because I can use these auto transpiled codebase directly as the artifact without needing a bundle (at least in dev). I expected the same to work for `avajs` such that I just reference the transpiled test files and the source maps help with the stack traces.

I was playing with the codebase and seems it works if the check to match stack trace with the test file does not check the extension strictly. I think this would work nicely even if the js is transpiled to another folder, given that source maps are generated during transpile. Find the change I made to try this in screenshot below, I basically changed line 40 to line 41 in `serialize-error.js`. It loads the files properly and generates the magic asserts with correct trace based on the sourcemap.

![image](https://user-images.githubusercontent.com/52130524/128320340-f498e0d5-9bf8-49c2-bc02-725b65b8e17b.png)

Do you think this could be something that can be supported, maybe under a configuration flag or so? @novemberborn  I think all of the typescript projects that do not bundle should work with this approach without needing `@ava/typescript`.

**Comment by novemberborn** [comment]
> unfortunately, es modules do not work with the `@ava/typescript` yet.

If you're game @jiby-gh, it shouldn't be too hard to implement, see https://github.com/avajs/typescript/issues/5#issuecomment-894663356.

> Do you think this could be something that can be supported, maybe under a configuration flag or so?

I don't quite follow, sorry. What is your suggestion?
