### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Kikobeats** [avajs/ava#2940]
Under ava@3, the test is working fine:

```
npx ava test/helpers/get-lines.js

  7 tests passed
```

However, after install ava@4, there is no way the test can be executed:

```
npx ava test/helpers/get-lines.js

  Uncaught exception in test/helpers/get-lines.js

  SyntaxError: Cannot use import statement outside a module

  ✖ test/helpers/get-lines.js exited with a non-zero exit code: 1
  ─

  1 uncaught exception
```

The [test file](https://github.com/microlinkhq/www/blob/master/test/helpers/get-lines.js) is quite simple; Looks like ava@4 can't resolve the [import statement there](https://github.com/microlinkhq/www/blob/master/test/helpers/get-lines.js#L3) properly; the source code is [just exporting an ES default method](https://github.com/microlinkhq/www/blob/439f754310dc5d8d0ecfaca4fe8abbd15c4f99fe/src/helpers/get-lines.js).

I guess that's the thing `esm` will be done at ava@3 and now is leveraging into Node.js internals.

My environment is:

```
npx envinfo --binaries --system

  System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 6.07 GB / 32.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.13.1 - ~/.local/share/nvm/v16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.local/share/nvm/v16.13.1/bin/npm
```

**Comment by novemberborn** [comment]
I see you've been using the `esm` package for ESM. AVA 3 recognized that package so the test files were actually loaded by `esm`. AVA 4 no longer recognizes the package and so the test file is treated no different than Node.js would. In your case, `.js` files are treated as CommonJS modules and so you cannot use `import`. You'd have to switch to full ESM (`.mjs` files or `"type": "module" in `package.json`) for it to work, or precompile or use a loader hook to convert to CommonJS on the fly.

**Comment by mjpelmear** [comment]
Hello,

Is there an example of any of these solutions anywhere? (Simply setting `"type": "module"` breaks everything for us.)

I love ava (and can't stand the other alternatives), but it's been a struggle to just be able to "import" since we first started using ava years ago, and it would be nice to upgrade to 4.* without having to spend a week figuring out how to continue to do that. Presumably there is a way to tell it to continue using the `esm` package to do this? (I can't find any documentation explaining how to upgrade from a setup relying on esm for ava < 4.*, and the explanation [here](https://github.com/avajs/ava/blob/main/docs/recipes/babel.md) isn't really helpful)

**Comment by novemberborn** [comment]
@mjpelmear you need to figure out how to use actual ESM. Support for the `esm` package has been removed. It's also not had an update in ~3 years.

AVA 4 is just following Node.js behavior.

**Comment by aht360** [comment]
Hello!
Do we have any updates about that issue?

**Comment by vedmant** [comment]
Just tried to use ava and first problem is this one, so anyone figured out what's the proper way to use ava 4? Or should I downgrade to ava 3?
