### ISSUE TITLE
`ava --version` returns unknown

### ISSUE THREAD

**Issue by broofa** [avajs/ava#2942]
In a nutshell ...

```
$ npm install -D ava

$ npm ls ava
/Users/kieffer/codepen/cp/cpcompiler/processors/sass
`-- ava@4.0.1

$ type ava
ava is hashed (./node_modules/.bin/ava)

$ ava --version
unknown
```

**Comment by novemberborn** [comment]
This used to work with v3, how strange!

**Comment by jopemachine** [comment]
I think it is an issue of `yargs`.

In [this code](https://github.com/yargs/yargs/blob/main/lib/platform-shims/esm.mjs#L24), yargs's `platform-shims/esm.mjs` takes different value on `mainFilename` with `platform-shims/cjs.ts`.

And in my thought, because this line stores the wrong value in the `mainFilename` in ESM, `yargs` cannot find ava's `package.json` in the `kPkgUp` function.

Maybe, I think this line needs to be changed like below or something.

```js
const mainFilename = __dirname.substring(0, __dirname.lastIndexOf('node_modules'));
```
