### ISSUE TITLE
Cache source-map urls should use absolute paths.

### ISSUE THREAD

**Issue by jamestalmage** [avajs/ava#817]
I run WIndows tests in Parallels, where my OSX homedir is mapped to the `Z:` drive. Many of our tests use the `--no-cache` option which causes our normal caching behavior to be redirected to a temp directory so there are no collisions between runs. Unfortunately, there's no way to represent a relative path between the `Z:` and `C:` drive.

Once https://github.com/thlorenz/convert-source-map/pull/41 is merged, we should be able to just attach the sourceMapUrl comments with absolute paths.

**Comment by novemberborn** [comment]
We need to update the minimum `convert-source-map` version in `package.json`. Then we should be able to use absolute paths here: https://github.com/avajs/ava/blob/dd9e8b2effe541f9f232ee622452343dac5895dd/lib/caching-precompiler.js#L77:L78

**Comment by kugtong33** [comment]
@novemberborn , hi I'm a beginner and would like to help on this, is this still open?

**Comment by novemberborn** [comment]
Yup go for it @kugtong33!

**Comment by kugtong33** [comment]
@novemberborn 

I looked at the instances where the caching precompiler are used and see if there are instances that the `options.path` would return a relative path, for `api.js`, `profile.js`, `fork.js`, `hooks.js` , all would return a unique temp directory name or ava cache absolute paths, usually where `node_modules/.cache/ava` is located.

Am I missing something? , because if there is an instance that a relative path would be added on `options.path`, I would then check first if the map path is absolute before adding it, else retain the relative map path.
