### ISSUE TITLE
Faulty code does not throw an error

### ISSUE THREAD

**Issue by Timyipstudio** [avajs/ava#983]
```js
test("foo update", t => {
	try {
		console.log(foo);
		console.log(bar);

		var foo = 1;
		let bar = 2;
	} catch (e) {
		t.is(e.name, 'ReferenceError')
	}
});
```

when i run code above. it didn't throw a error

**Comment by jfmengels** [comment]
I think it's because the test code is compiled by Babel, and the compiled code is not trying to cause `ReferenceError` to be thrown when a variable declared with `let`/`const` is used before its declaration.

Not sure there is anything to be done about this.

(By the way, has there been a discussion to only compile only what is needed based on what is supported in the node version that runs the tests? Couldn't find one)

**Comment by sindresorhus** [comment]
Looks like a Babel bug or caveat indeed.

@Timyipstudio Could you maybe try asking about it in the [Babel support channels](https://github.com/babel/babel#looking-for-support)?

Sidenote: If you want to check if something throws, use `t.throws()` instead.

**Comment by sindresorhus** [comment]
@jfmengels Yup: https://github.com/avajs/ava/issues/148

**Comment by novemberborn** [comment]
I could only find <https://github.com/babel/babel/issues/563> on this, and there is some [TDZ related code ](https://github.com/babel/babel/blob/d7533e899f3d89bd7269a36618a3d6606cc399db/packages/babel-plugin-transform-es2015-block-scoping/src/tdz.js) in the `block-scoping` plugin. So maybe this is a Babel bug or maybe Babel decided it's too hard to fix.

As far as AVA goes, we can do better by not transpiling language features that are supported by the Node.js runtime, which is #148.
